# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftProjects' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit' 
  pod 'Kingfisher' 
  pod 'CYLTabBarController'

  #07-PokedexGo
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for SwiftProjects

end
